// CFO AI Database Types for Supabase
export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string;
          name: string;
          slug: string;
          plan: 'free' | 'starter' | 'professional' | 'enterprise';
          status: 'active' | 'suspended' | 'cancelled';
          settings: Json;
          created_at: string;
          updated_at: string | null;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          plan?: 'free' | 'starter' | 'professional' | 'enterprise';
          status?: 'active' | 'suspended' | 'cancelled';
          settings?: Json;
          created_at?: string;
          updated_at?: string | null;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          plan?: 'free' | 'starter' | 'professional' | 'enterprise';
          status?: 'active' | 'suspended' | 'cancelled';
          settings?: Json;
          created_at?: string;
          updated_at?: string | null;
          created_by?: string | null;
        };
      };
      user_profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          phone: string | null;
          timezone: string;
          locale: string;
          preferences: Json;
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          timezone?: string;
          locale?: string;
          preferences?: Json;
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          timezone?: string;
          locale?: string;
          preferences?: Json;
          created_at?: string;
          updated_at?: string | null;
        };
      };
      user_tenants: {
        Row: {
          id: string;
          user_id: string;
          tenant_id: string;
          role: 'owner' | 'admin' | 'approver' | 'analyst' | 'viewer';
          status: 'active' | 'inactive' | 'invited';
          permissions: Json;
          created_at: string;
          updated_at: string | null;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          tenant_id: string;
          role: 'owner' | 'admin' | 'approver' | 'analyst' | 'viewer';
          status?: 'active' | 'inactive' | 'invited';
          permissions?: Json;
          created_at?: string;
          updated_at?: string | null;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          tenant_id?: string;
          role?: 'owner' | 'admin' | 'approver' | 'analyst' | 'viewer';
          status?: 'active' | 'inactive' | 'invited';
          permissions?: Json;
          created_at?: string;
          updated_at?: string | null;
          created_by?: string | null;
        };
      };
      invoices: {
        Row: {
          id: string;
          tenant_id: string;
          job_id: string | null;
          file_id: string;
          invoice_number: string;
          invoice_type: 'invoice' | 'credit_note' | 'debit_note' | null;
          cufe: string | null;
          issue_date: string;
          due_date: string | null;
          supplier_nit: string;
          supplier_name: string;
          supplier_address: string | null;
          supplier_city: string | null;
          supplier_phone: string | null;
          supplier_email: string | null;
          buyer_nit: string;
          buyer_name: string;
          buyer_address: string | null;
          buyer_city: string | null;
          subtotal: number;
          tax_amount: number;
          discount_amount: number;
          total_amount: number;
          currency_code: string;
          source_format: 'xml_ubl' | 'pdf_ocr' | 'image_ocr' | null;
          confidence_score: number | null;
          needs_review: boolean;
          review_notes: string | null;
          status: 'parsed' | 'classified' | 'calculated' | 'reviewed' | 'approved' | 'exported';
          created_at: string;
          updated_at: string | null;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          job_id?: string | null;
          file_id: string;
          invoice_number: string;
          invoice_type?: 'invoice' | 'credit_note' | 'debit_note' | null;
          cufe?: string | null;
          issue_date: string;
          due_date?: string | null;
          supplier_nit: string;
          supplier_name: string;
          supplier_address?: string | null;
          supplier_city?: string | null;
          supplier_phone?: string | null;
          supplier_email?: string | null;
          buyer_nit: string;
          buyer_name: string;
          buyer_address?: string | null;
          buyer_city?: string | null;
          subtotal: number;
          tax_amount?: number;
          discount_amount?: number;
          total_amount: number;
          currency_code?: string;
          source_format?: 'xml_ubl' | 'pdf_ocr' | 'image_ocr' | null;
          confidence_score?: number | null;
          needs_review?: boolean;
          review_notes?: string | null;
          status?: 'parsed' | 'classified' | 'calculated' | 'reviewed' | 'approved' | 'exported';
          created_at?: string;
          updated_at?: string | null;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          job_id?: string | null;
          file_id?: string;
          invoice_number?: string;
          invoice_type?: 'invoice' | 'credit_note' | 'debit_note' | null;
          cufe?: string | null;
          issue_date?: string;
          due_date?: string | null;
          supplier_nit?: string;
          supplier_name?: string;
          supplier_address?: string | null;
          supplier_city?: string | null;
          supplier_phone?: string | null;
          supplier_email?: string | null;
          buyer_nit?: string;
          buyer_name?: string;
          buyer_address?: string | null;
          buyer_city?: string | null;
          subtotal?: number;
          tax_amount?: number;
          discount_amount?: number;
          total_amount?: number;
          currency_code?: string;
          source_format?: 'xml_ubl' | 'pdf_ocr' | 'image_ocr' | null;
          confidence_score?: number | null;
          needs_review?: boolean;
          review_notes?: string | null;
          status?: 'parsed' | 'classified' | 'calculated' | 'reviewed' | 'approved' | 'exported';
          created_at?: string;
          updated_at?: string | null;
          created_by?: string | null;
        };
      };
      files: {
        Row: {
          id: string;
          tenant_id: string;
          message_id: string | null;
          filename: string;
          original_filename: string | null;
          storage_path: string;
          mime_type: string | null;
          file_size: number | null;
          file_hash: string | null;
          source: 'email' | 'upload' | 'zip_extract';
          status: 'stored' | 'processing' | 'processed' | 'error' | 'deleted';
          metadata: Json;
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          message_id?: string | null;
          filename: string;
          original_filename?: string | null;
          storage_path: string;
          mime_type?: string | null;
          file_size?: number | null;
          file_hash?: string | null;
          source: 'email' | 'upload' | 'zip_extract';
          status?: 'stored' | 'processing' | 'processed' | 'error' | 'deleted';
          metadata?: Json;
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          message_id?: string | null;
          filename?: string;
          original_filename?: string | null;
          storage_path?: string;
          mime_type?: string | null;
          file_size?: number | null;
          file_hash?: string | null;
          source?: 'email' | 'upload' | 'zip_extract';
          status?: 'stored' | 'processing' | 'processed' | 'error' | 'deleted';
          metadata?: Json;
          created_at?: string;
          updated_at?: string | null;
        };
      };
      processing_jobs: {
        Row: {
          id: string;
          tenant_id: string;
          message_id: string | null;
          file_id: string | null;
          job_type: 'email_process' | 'file_parse' | 'manual_upload';
          status: 'queued' | 'parsing' | 'llm_classify' | 'tax_compute' | 'ready_for_review' | 'approved' | 'exported' | 'error' | 'cancelled';
          priority: number;
          attempts: number;
          max_attempts: number;
          started_at: string | null;
          finished_at: string | null;
          error_message: string | null;
          progress_data: Json;
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          message_id?: string | null;
          file_id?: string | null;
          job_type: 'email_process' | 'file_parse' | 'manual_upload';
          status?: 'queued' | 'parsing' | 'llm_classify' | 'tax_compute' | 'ready_for_review' | 'approved' | 'exported' | 'error' | 'cancelled';
          priority?: number;
          attempts?: number;
          max_attempts?: number;
          started_at?: string | null;
          finished_at?: string | null;
          error_message?: string | null;
          progress_data?: Json;
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          message_id?: string | null;
          file_id?: string | null;
          job_type?: 'email_process' | 'file_parse' | 'manual_upload';
          status?: 'queued' | 'parsing' | 'llm_classify' | 'tax_compute' | 'ready_for_review' | 'approved' | 'exported' | 'error' | 'cancelled';
          priority?: number;
          attempts?: number;
          max_attempts?: number;
          started_at?: string | null;
          finished_at?: string | null;
          error_message?: string | null;
          progress_data?: Json;
          created_at?: string;
          updated_at?: string | null;
        };
      };
      classifications: {
        Row: {
          id: string;
          invoice_id: string;
          expense_kind: 'goods' | 'services' | 'professional_fees';
          is_large_taxpayer: boolean | null;
          city_code: string | null;
          expense_category: string | null;
          confidence_score: number;
          rationale: string | null;
          model_version: string | null;
          processing_time: number | null;
          is_reviewed: boolean;
          reviewed_by: string | null;
          reviewed_at: string | null;
          review_changes: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          expense_kind: 'goods' | 'services' | 'professional_fees';
          is_large_taxpayer?: boolean | null;
          city_code?: string | null;
          expense_category?: string | null;
          confidence_score: number;
          rationale?: string | null;
          model_version?: string | null;
          processing_time?: number | null;
          is_reviewed?: boolean;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          review_changes?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          expense_kind?: 'goods' | 'services' | 'professional_fees';
          is_large_taxpayer?: boolean | null;
          city_code?: string | null;
          expense_category?: string | null;
          confidence_score?: number;
          rationale?: string | null;
          model_version?: string | null;
          processing_time?: number | null;
          is_reviewed?: boolean;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          review_changes?: Json | null;
          created_at?: string;
        };
      };
      tax_calculations: {
        Row: {
          id: string;
          invoice_id: string;
          classification_id: string;
          iva_base: number;
          reteiva_base: number;
          retefuente_base: number;
          ica_base: number;
          iva_amount: number;
          reteiva_amount: number;
          retefuente_amount: number;
          ica_amount: number;
          iva_rate: number | null;
          reteiva_rate: number | null;
          retefuente_rate: number | null;
          ica_rate: number | null;
          applied_rules: Json | null;
          calculation_details: Json | null;
          calculated_at: string;
          rules_version: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          classification_id: string;
          iva_base?: number;
          reteiva_base?: number;
          retefuente_base?: number;
          ica_base?: number;
          iva_amount?: number;
          reteiva_amount?: number;
          retefuente_amount?: number;
          ica_amount?: number;
          iva_rate?: number | null;
          reteiva_rate?: number | null;
          retefuente_rate?: number | null;
          ica_rate?: number | null;
          applied_rules?: Json | null;
          calculation_details?: Json | null;
          calculated_at?: string;
          rules_version?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          classification_id?: string;
          iva_base?: number;
          reteiva_base?: number;
          retefuente_base?: number;
          ica_base?: number;
          iva_amount?: number;
          reteiva_amount?: number;
          retefuente_amount?: number;
          ica_amount?: number;
          iva_rate?: number | null;
          reteiva_rate?: number | null;
          retefuente_rate?: number | null;
          ica_rate?: number | null;
          applied_rules?: Json | null;
          calculation_details?: Json | null;
          calculated_at?: string;
          rules_version?: string | null;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];